# main text of home
name: François Corbel
bio: A human who speaks with computers to create games.
description: My projects and résumé
picture: assets/images/profile.png
empty: assets/images/1px-alpha.png
permalink: /:title/

resume: true
projects: true
about: false
blog: false

url: https://fcvalise.github.io
jekyll-mentions:
    base_url: https://github.com
analytics-google: 'UA-105835301-1'

twitter: FcValise
youtube: watch?v=dAnAuwoRoA0&list=PLhK30YO4FlvUpFmLvh-9CPIiRMCu6MN4z
github: fcvalise
email: francois.corbel@gmail.com
steam: search/?developer=Octo%20Studio
itchio: octostudio
linkedin: francoiscorbel

# if you don't need pagination, comment the *paginate* configs below
#paginate: 5
#paginate_path: "blog/:num/"

# do you want to show the "read time" of the posts?
#read-time: true

# do you want to show the "tags" inside the posts?
show-tags: false

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
